### ISSUE TITLE
Missing LocalAllocHandle helper..?

### ISSUE THREAD

**Issue by Erutan409** [jpassing/dotnet-crypto-utils#1]
Per your article's walk-through:

`Note that the code uses a custom helper class LocalAllocHandle to handle memory allocations.`

Is this intentionally missing from your repository?

**Comment by jpassing** [comment]
You can find the class in `UnsafeNativeMethods.cs`:

https://github.com/jpassing/dotnet-crypto-utils/blob/5fd689acde441fbf1c006a7c25d04bf4c7594580/CryptoUtils/UnsafeNativeMethods.cs#L91

**Comment by Erutan409** [comment]
@jpassing Oh, nice. My apologies for missing it.

**Comment by jpassing** [comment]
No worries :)
